[package]
name = "stunnel"
version = "0.1.0"
authors = ["Benjamin Cheng <ben@bcheng.cf>"]

[dependencies]
bytes = "0.4"
error-chain = "0.10"
futures = "0.1"
native-tls = "0.1"
serde = "1.0"
serde_derive = "1.0"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-tls = "0.1"
toml = "0.4"
